# These are supported funding model platforms

github: [merouaneamqor] # Replace with your GitHub username
patreon: # Replace with your Patreon username
open_collective: # Replace with your Open Collective username
ko_fi: # Replace with your Ko-fi username
tidelift: # Replace with your Tidelift platform/project
community_bridge: # Replace with your Community Bridge project
liberapay: # Replace with your Liberapay username
issuehunt: # Replace with your IssueHunt username
otechie: # Replace with your Otechie username
custom: # Replace with a custom sponsorship URL
